version: '3'

services:

  jupyter:
    image: mnagaku/lc-minimal-notebook
    ports:
      - "8888:8888"
    command: bash -c "git clone --depth 1 https://github.com/mnagaku/janog41-auto-taiji.git ; jupyter notebook --NotebookApp.token=''"